# Generated by Django 4.2.7 on 2023-11-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_tag',
            field=models.CharField(default=str, max_length=10),
            preserve_default=False,
        ),
    ]
