# Generated by Django 4.2.7 on 2023-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_html_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='html_tag',
            field=models.CharField(max_length=20),
        ),
    ]
